### ISSUE TITLE
Unable to start plugin with Nexus 3.2.0

### ISSUE THREAD

**Issue by testuser7** [sonatype-nexus-community/nexus-repository-apt#2]
Hi,

I'm getting this error after start bundle:
```
karaf@root()> bundle:start 14
2017-01-12 13:34:09,913+0100 INFO  [Karaf local console user karaf] *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - ACTIVATING net.staticsnow.nexus-repository-apt [14]
2017-01-12 13:34:10,676+0100 WARN  [Karaf local console user karaf] *SYSTEM org.sonatype.nexus.extender.NexusBundleTracker - BROKEN net.staticsnow.nexus-repository-apt [14]
ERROR: Bundle org.sonatype.nexus.extender [132] EventDispatcher: Error during dispatch. (com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for net.staticsnow.nexus.repository.apt.internal.hosted.AptHostedFacet annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

1 error)
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for net.staticsnow.nexus.repository.apt.internal.hosted.AptHostedFacet annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.eclipse.sisu.launch.SisuBundlePlan.inject(SisuBundlePlan.java:78)
        at org.eclipse.sisu.launch.SisuBundlePlan.prepare(SisuBundlePlan.java:50)
        at org.eclipse.sisu.launch.SisuTracker.prepare(SisuTracker.java:186)
        at org.sonatype.nexus.extender.NexusBundleTracker.prepare(NexusBundleTracker.java:68)
        at org.eclipse.sisu.launch.SisuTracker.addingBundle(SisuTracker.java:129)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:415)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
        at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:916)
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:835)
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:517)
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2216)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
        at org.apache.karaf.bundle.command.Start.executeOnBundle(Start.java:38)
        at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:64)
        at org.apache.karaf.bundle.command.BundlesCommand.execute(BundlesCommand.java:54)
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83)
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67)
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
        at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:270)
        at java.lang.Thread.run(Thread.java:745)
karaf@root()> 2017-01-12 13:34:10,747+0100 ERROR [FelixDispatchQueue] *SYSTEM org.sonatype.nexus.extender - FrameworkEvent ERROR - org.sonatype.nexus.extender
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for net.staticsnow.nexus.repository.apt.internal.hosted.AptHostedFacet annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) [na:na]
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) [na:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) [na:na]
        at com.google.inject.Guice.createInjector(Guice.java:99) [na:na]
        at com.google.inject.Guice.createInjector(Guice.java:73) [na:na]
        at com.google.inject.Guice.createInjector(Guice.java:62) [na:na]
        at org.eclipse.sisu.launch.SisuBundlePlan.inject(SisuBundlePlan.java:78) [na:na]
        at org.eclipse.sisu.launch.SisuBundlePlan.prepare(SisuBundlePlan.java:50) [na:na]
        at org.eclipse.sisu.launch.SisuTracker.prepare(SisuTracker.java:186) [na:na]
        at org.sonatype.nexus.extender.NexusBundleTracker.prepare(NexusBundleTracker.java:68) [na:na]
        at org.eclipse.sisu.launch.SisuTracker.addingBundle(SisuTracker.java:129) [na:na]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469) [org.osgi.core-6.0.0.jar:na]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:415) [org.osgi.core-6.0.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.osgi.core-6.0.0.jar:na]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.osgi.core-6.0.0.jar:na]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [org.osgi.core-6.0.0.jar:na]
        at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:916) [na:na]
        at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:835) [na:na]
        at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:517) [na:na]
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4541) [na:na]
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2216) [na:na]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144) [na:na]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998) [na:na]
        at org.apache.karaf.bundle.command.Start.executeOnBundle(Start.java:38) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:64) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.execute(BundlesCommand.java:54) [na:na]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406) [na:na]
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119) [na:na]
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94) [na:na]
        at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:270) [na:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by DarthHater** [comment]
Work in #4 should resolve this.

**Comment by mpoindexter** [comment]
Implemented changed from @DarthHater
