### ISSUE TITLE
missing requirement after install

### ISSUE THREAD

**Issue by thorus90** [sonatype-nexus-community/nexus-repository-apt#35]
* **What are you trying to do?**
I'm trying to build and install the plugin
* **What did I do**
I did build the plugin on a machine with Java 1.8.0_111 which got his dependencies from our old nexus 2, because it already had the right repos in place (with our nexus 3 I can't even download the dependencies).
I copied the content of ~/.m2/repository/net/staticsnow/nexus-repository-apt/1.0.4/ to the specified directory in the install process.
I modified the file according to the documentation
* **Error Message**
```
2018-02-14 15:09:41,450+0100 ERROR [jetty-main-1]  *SYSTEM org.sonatype.nexus.bootstrap.jetty.JettyServer - Failed to start
java.lang.RuntimeException: org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=nex
us-oss-feature; type=karaf.feature; version="[3.7.1.02,3.7.1.02]"; filter:="(&(osgi.identity=nexus-oss-feature)(type=karaf.feature)(version>=3.7.1.02)(version
<=3.7.1.02))" [caused by: Unable to resolve nexus-oss-feature/3.7.1.02: missing requirement [nexus-oss-feature/3.7.1.02] osgi.identity; osgi.identity=nexus-re
pository-apt; type=karaf.feature [caused by: Unable to resolve nexus-repository-apt/1.0.4: missing requirement [nexus-repository-apt/1.0.4] osgi.identity; osg
i.identity=net.staticsnow.nexus-repository-apt; type=osgi.bundle; version="[1.0.4,1.0.4]"; resolution:=mandatory [caused by: Unable to resolve net.staticsnow.
nexus-repository-apt/1.0.4: missing requirement [net.staticsnow.nexus-repository-apt/1.0.4] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.sonatype.
nexus.blobstore.api)(version>=3.8.0))"]]]
        at org.sonatype.nexus.extender.NexusContextListener.contextInitialized(NexusContextListener.java:176)
        at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:47)
        at org.sonatype.nexus.bootstrap.osgi.ListenerTracker.addingService(ListenerTracker.java:1)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261)
        at org.sonatype.nexus.bootstrap.osgi.BootstrapListener.contextInitialized(BootstrapListener.java:101)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1406)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1368)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:522)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:92)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
```
* **Anything else?**
Any ideas what I did wrong?

**Comment by DarthHater** [comment]
What version of Nexus Repo are you trying to run the plugin on? Looks like 3.7.1-02, the error states you need 3.8.0 for the version of the plugin you are running. If you want to run one compatible with 3.7.1-02 you should be able to build from this tag: https://github.com/sonatype-nexus-community/nexus-repository-apt/releases/tag/1.0.2

**Comment by derjohn** [comment]
@DarthHater Probably the same as my issue https://github.com/sonatype-nexus-community/nexus-repository-apt/issues/40....

@thorus90 You can try my workaround mentioned in #40 ....

**Comment by thorus90** [comment]
Thanks updating to, in the meantime, nexus 3.9, rebuilding the plugin solved my issue.

**Comment by mpoindexter** [comment]
Closing as this should be addressed in newer releases
