### ISSUE TITLE
Unable to resolve, missing requirement osgi.wiring.package

### ISSUE THREAD

**Issue by ghost** [sonatype-nexus-community/nexus-repository-apt#7]
Just trying to install this bundle into Nexus 3.2.0-01

Following the temporary instructions to try out the plugin, I get to bundle:start <ID> and get the following error:

```
238 | Installed | 200 | 1.0.2                      | net.staticsnow:nexus-repository-apt
karaf@root()> bundle:start 238
2017-04-13 18:10:41,828+0100 ERROR [Karaf local console user karaf] *SYSTEM org.apache.karaf.shell.support.ShellUtil - Exception caught while executing command
org.apache.karaf.shell.support.MultiException: Error executing command on bundles:
        Error starting bundle 238: Unable to resolve net.staticsnow.nexus-repository-apt [238](R 238.0): missing requirement [net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0))]
        at org.apache.karaf.shell.support.MultiException.throwIf(MultiException.java:61) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:69) [na:na]
        at org.apache.karaf.bundle.command.BundlesCommand.execute(BundlesCommand.java:54) [na:na]
        at org.apache.karaf.shell.impl.action.command.ActionCommand.execute(ActionCommand.java:83) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:67) [na:na]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:87) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480) [na:na]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406) [na:na]
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182) [na:na]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119) [na:na]
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94) [na:na]
        at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.run(ConsoleSessionImpl.java:270) [na:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
        Suppressed: java.lang.Exception: Error starting bundle 238: Unable to resolve net.staticsnow.nexus-repository-apt [238](R 238.0): missing requirement [net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0))]
                at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:66) [na:na]
                ... 12 common frames omitted
        Caused by: org.osgi.framework.BundleException: Unable to resolve net.staticsnow.nexus-repository-apt [238](R 238.0): missing requirement [net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0))]
                at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
                at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
                at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
                at org.apache.karaf.bundle.command.Start.executeOnBundle(Start.java:38)
                at org.apache.karaf.bundle.command.BundlesCommand.doExecute(BundlesCommand.java:64)
                ... 12 common frames omitted

Error executing command: Error executing command on bundles:
        Error starting bundle 238: Unable to resolve net.staticsnow.nexus-repository-apt [238](R 238.0): missing requirement [net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [238](R 238.0)] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.base)(version>=21.0.0))]
```

This is after building from a clean checkout and following the readme.

**Comment by mpoindexter** [comment]
It looks like the version of com.google.common.base the plugin depends on doesn't match the version of com.google.common.base in that version of Nexus.  Can you see if this happens with Nexus 3.2.1

**Comment by ghost** [comment]
Works nicely on 3.3.1

(Also apologies for the massive delay in getting back to you on this!)
