### ISSUE TITLE
Auto startup 

### ISSUE THREAD

**Issue by MikkelHJuul** [sonatype-nexus-community/nexus-repository-apt#92]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Add file to <nexus-root>/<nexus-version>/system/net/staticsnow/nexus-repository-apt/<vers>/nexus-repository-apt-<vers>.jar
reference this file in startup.properties:
reference\:file\:net/staticsnow/nexus-repository-apt/<vers>/nexus-repository-apt-<vers>.jar = 30
classloading works
<><><><>
prevent use of screen to deploy application
<><><><>
I specifically compiled/installed branch UpgradeToThreeDotFifteen as vers.=1.0.10
it works in karafConsoleMode (bundle.install)

* **What feature or behavior is this required for?**
Automation of bundle-injection at startup

* **How could we solve this issue? (Not knowing is okay!)**
slower/delayed start-up
change wiring/fallback to delayed wiring of com.orientechnologies.common.concur 

* **Anything else?**
console Err out
ERROR: Bundle net.staticsnow.nexus-repository-apt [52] Error starting reference:file:system/net/staticsnow/nexus-repository-apt/1.0.10/nexus-repository-apt-1.0.10.jar (org.osgi.framework.BundleException: Unable to resolve net.staticsnow.nexus-repository-apt [52](R 52.0): missing requirement [net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))])
org.osgi.framework.BundleException: Unable to resolve net.staticsnow.nexus-repository-apt [52](R 52.0): missing requirement [net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
2019-01-14 13:58:31,207+0000 ERROR [FelixDispatchQueue] *SYSTEM net.staticsnow.nexus-repository-apt - FrameworkEvent ERROR - net.staticsnow.nexus-repository-apt
org.osgi.framework.BundleException: Unable to resolve net.staticsnow.nexus-repository-apt [52](R 52.0): missing requirement [net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0)) Unresolved requirements: [[net.staticsnow.nexus-repository-apt [52](R 52.0)] osgi.wiring.package; (&(osgi.wiring.package=com.orientechnologies.common.concur)(version>=2.2.0))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4132)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)

**Comment by MikkelHJuul** [comment]
I should read the manual... both places...
